### ISSUE TITLE
Update nvidia-open kernel driver to the latest version [565.57.01].

### ISSUE THREAD

**Issue by UG40A** [CachyOS/copr-linux-cachyos#10]
New version contains major bug-fixes for power management stability, fixes related kernel panic and vulkan rendering problems on GNOME. 
Fedora was already added this (latest) version at repositories and now we'll have version mismatch: 565 for userspace and 560 for kernel module. 

P.S.: Also, It'll be great, if we (additionally) can pre-build unified kernel modules as an akmod, that can be used in cachyos and vanilla fedora kernels simultaneously. 

Thank you for your great work!

**Comment by andersrh** [comment]
Hello. Which fedora version are you on? i checked on fedora 40 and it's still using 560

**Comment by andersrh** [comment]
The issue with prebuilding kernel modules is that they will only work with the specific kernel as they are built against because they are saved in /lib/modules/_kernelname_

thats why we build them with the kernels as we do currently.
