### ISSUE TITLE
Should the packages kernel-tools(-libs) also be replaced in Silverblue?

### ISSUE THREAD

**Issue by zrooda** [CachyOS/copr-linux-cachyos#12]
Fedora Silverblue image includes the `kernel-tools` and `kernel-tools-libs` packages, but the documentation for a Silverblue install at https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos doesn't include those to be replaced. Should they be?

**Comment by 1Naim** [comment]
Nope, you can keep the ones from Fedora. Reason why we don't build it.

**Comment by zrooda** [comment]
Thanks, appreciate the response (and packaging this beast of a kernel for Fedora)!
