### ISSUE TITLE
Copr kernel doesnt load nvidia

### ISSUE THREAD

**Issue by EisregenHaha** [CachyOS/copr-linux-cachyos#16]
So the cachyos-lto kernel on the copr for fedora wont load nvidia and just falls back to noveau.
https://copr.fedorainfracloud.org/coprs/bieszczaders/kernel-cachyos-lto/
I tried the non-copr akmods version to build but it still always just throws and error. 
happening  since a month.

[560.35.03-1-for-6.12.0-cb1.0.lto.fc41.x86_64.failed.log](https://github.com/user-attachments/files/17837890/560.35.03-1-for-6.12.0-cb1.0.lto.fc41.x86_64.failed.log)

idrk what to do

System is Fedora 41 on an Nvidia RTX 3080 with a 12700k

**Comment by 1Naim** [comment]
Why are you still on 560.35.03? RPMFusion is on 565.

**Comment by EisregenHaha** [comment]
> It is still beta, but the RPMFusion maintainers has pushed them due to vulnerabilities in the latest new feature branch driver. See https://ohioix.mm.fcix.net/rpmfusion/nonfree/fedora/updates/41/x86_64/repoview/index.html, 565 is on the stable repos.

not sure then, update doesnt give them to me. i have all rpmfusion repos enabled, both free and nonfree

**Comment by 1Naim** [comment]
Can you show me the output of `ls /etc/yum.repos.d`

**Comment by 1Naim** [comment]
> is the issue that im on 560

Currently all 560+ drivers are incompatible with 6.12 kernel, the difference is 565 has been patched, both by us through our prebuilt kernel modules and by the RPMFusion maintainers.

**Comment by EisregenHaha** [comment]
> > is the issue that im on 560
> 
> Currently all 560+ drivers are incompatible with 6.12 kernel, the difference is 565 has been patched, both by us through our prebuilt kernel modules and by the RPMFusion maintainers.

alright thanks i'll update when im home

**Comment by EisregenHaha** [comment]
> > is the issue that im on 560
> 
> Currently all 560+ drivers are incompatible with 6.12 kernel, the difference is 565 has been patched, both by us through our prebuilt kernel modules and by the RPMFusion maintainers.

alright for some reason the nonfree rpmfusion repo was disabled so i only had 560 from the discovery store. after enabling them i have 565 now. weird that i installed them and they didnt automatically enable

**Comment by EisregenHaha** [comment]
issue is not completed, i still boot into a black screen even with the new drivers even though akmods now works. i dont know why
