### ISSUE TITLE
Copr kernel black screen

### ISSUE THREAD

**Issue by EisregenHaha** [CachyOS/copr-linux-cachyos#17]
For some reason previous issue #16 was just closed but still problems arent solved, now it boots into a black screen, even completely reinstalled fedora to see if its my system but nah.

**Comment by EisregenHaha** [comment]
@1Naim any idea about this?

**Comment by ptr1337** [comment]
> @1Naim any idea about this?

Likely its due fedora missing to have the patch for 6.12. Nothing we can do here. That needs to be fixed by rpmfusion. I wrote them via email already to add the patch (they already did) but its not pushed to stable yet.

**Comment by EisregenHaha** [comment]
> > @1Naim any idea about this?
> 
> Likely its due fedora missing to have the patch for 6.12. Nothing we can do here. That needs to be fixed by rpmfusion. I wrote them via email already to add the patch (they already did) but its not pushed to stable yet.

oh alright thank you i'll just wait then

**Comment by 1Naim** [comment]
> > @1Naim any idea about this?
> 
> Likely its due fedora missing to have the patch for 6.12. Nothing we can do here. That needs to be fixed by rpmfusion. I wrote them via email already to add the patch (they already did) but its not pushed to stable yet.

Yes, should be pushed today. RPMFusion pushes packages on bull every Friday.

**Comment by EisregenHaha** [comment]
issue persists 

> > > @1Naim any idea about this?
> > 
> > 
> > Likely its due fedora missing to have the patch for 6.12. Nothing we can do here. That needs to be fixed by rpmfusion. I wrote them via email already to add the patch (they already did) but its not pushed to stable yet.
> 
> Yes, should be pushed today. RPMFusion pushes packages on bull every Friday.

**Comment by EisregenHaha** [comment]
> > > @1Naim any idea about this?
> > 
> > 
> > Likely its due fedora missing to have the patch for 6.12. Nothing we can do here. That needs to be fixed by rpmfusion. I wrote them via email already to add the patch (they already did) but its not pushed to stable yet.
> 
> Yes, should be pushed today. RPMFusion pushes packages on bull every Friday.

LTS works fine tho just tried

**Comment by 1Naim** [comment]
Patched module is still in testing, keep waiting.

**Comment by EisregenHaha** [comment]
> Patched module is still in testing, keep waiting.

oh alright my b thought it was pushed alr

**Comment by EisregenHaha** [comment]
alright i didnt wanna wait and just enabled testing repos, i'll close for now. thanks for the help and for the kernel yall
