### ISSUE TITLE
Unable to update to Fedora 41 Kinoite

### ISSUE THREAD

**Issue by nijahplays** [CachyOS/copr-linux-cachyos#5]
`error: No matches for 'libbpf' in repo 'copr:copr.fedorainfracloud.org:bieszczaders:kernel-cachyos-addons'`

![image](https://github.com/user-attachments/assets/e63befa4-8842-43d7-a381-91ab5c99bb4a)

**Comment by TrixieUA** [comment]
The libpf version in f41 is up to date enough so we didnt build it in our repo. Disable libbpf override with `rpm-ostree override reset libbpf`
